# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  images: |
    - name: grafana
      image: packages.public.utmonline.net/docker-images/bitnami/grafana:12.1.1-debian-12-r1
    - name: os-shell
      image: packages.public.utmonline.net/docker-images/bitnami/os-shell:12-debian-12-r50
  licenses: Apache-2.0
  tanzuCategory: application
apiVersion: v2
appversion: 12.1.3
dependencies:
- name: bitnami-common
  repository: oci://packages.public.utmonline.net/helm/helm-charts/
  tags:
  - bitnami-common
  version: 1.x.x
description: Grafana is an open source metric analytics and visualization suite for
  visualizing time series data that supports various types of data sources.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/grafana/img/grafana-stack-220x234.png
keywords:
- analytics
- monitoring
- metrics
- logs
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: grafana
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/grafana
version: 12.1.3
